/*
 * Godot Asset Library
 *
 * Godot Engine's asset library
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A paginated list of assets.
type PaginatedAssetList struct {
	// The requested page string.
	Page int32 `json:"page,omitempty"`
	// The requested page length.<br> **Note:** This can be higher than the total amount of items returned.
	PageLength int32 `json:"page_length,omitempty"`
	// The total string of pages available.<br> **Note:** If requesting a page higher than this value, a successful response will be returned (status code 200) but no items will be listed.
	Pages int32 `json:"pages,omitempty"`
	// The total string of items available.
	TotalItems int32          `json:"total_items,omitempty"`
	Result     []AssetSummary `json:"result,omitempty"`
}
