/*
 * Godot Asset Library
 *
 * Godot Engine's asset library
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An error returned by Laravel.
type ValidationError struct {
	Errors []string `json:"errors,omitempty"`
	// A generic error message.
	Message string `json:"message,omitempty"`
}
