/*
 * Godot Asset Library
 *
 * Godot Engine's asset library
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The requested resource was not found.
type NotFoundError struct {
	// A generic error message.
	Error_ string `json:"error,omitempty"`
}
