/*
 * Godot Asset Library
 *
 * Godot Engine's asset library
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ABCD. 
type AssetPreview struct {
	PreviewId string `json:"preview_id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Link string `json:"link,omitempty"`
	Thumbnail string `json:"thumbnail,omitempty"`
}
