/*
 * Godot Asset Library
 *
 * Godot Engine's asset library
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A category in which assets belong to. An asset can only belong to one category at a time. 
type Category struct {
	// The category's unique identifier.
	Id string `json:"id,omitempty"`
	// The category's name.
	Name string `json:"name,omitempty"`
	// The category's type (0 = Add-ons, 1 = Projects).
	Type_ string `json:"type,omitempty"`
}
