/*
 * Godot Asset Library
 *
 * Godot Engine's asset library
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// An asset version.
type AssetVersion struct {
	// The version's release date.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The version's custom download URL (if any). Will be an empty string if not set. 
	DownloadUrl string `json:"download_url,omitempty"`
	// The minor Godot version the asset version was declared to be compatible with (in `major.minor` format). 
	GodotVersion string `json:"godot_version,omitempty"`
	// The version identifier.
	VersionString string `json:"version_string,omitempty"`
}
